### ISSUE TITLE
Create github org

### ISSUE THREAD

**Issue by PWhiddy** [bnanner/SculpturePark#32]
Separate repos for website, framework, embed example, other tools

**Comment by torinmb** [comment]
I feel like it'd also be good to figure out a way of separating the documentation site into a separate repo

**Comment by PWhiddy** [comment]
@torinmb Did you do this yet? we can easily transfer this repo to it once its created

**Comment by PWhiddy** [comment]
@torinmb are we good to transfer this to bnanner?

**Comment by PWhiddy** [comment]
Done!
